export enum SubjectType {
  KOREAN = 'KOREAN',
  ENGLISH = 'ENGLISH',
  MATH = 'MATH',
  SCIENCE = 'SCIENCE',
  SOCIALSTUDIES = 'SOCIALSTUDIES',
  HISTORIES = 'HISTORIES',
  ART = 'ART',
  MUSIC = 'MUSIC',
  FOREIGNLANGUAGE = ' FOREIGNLANGUAGE',
  SELFDEVELOPMENT = ' SELFDEVELOPMENT',
  OTHER = ' OTHER',
}
