# Use the official Node.js image as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the NestJS application
RUN npm run build

# Expose the application port
EXPOSE $SERVER_PORT

# Command to run the application, using the SERVER_PORT environment variable
CMD ["sh", "-c", "node dist/main --port ${SERVER_PORT}"]
